barrios=['Boedo',
 'Palermo',
 'Palermo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Parque Patricios',
 'Parque Patricios',
 'Villa Pueyrredón',
 'Boedo',
 'Boedo',
 'Abasto',
 'Flores',
 'Flores',
 'Flores',
 'Flores',
 'Nuñez',
 'Nuñez',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Floresta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Caballito',
 'Chacarita',
 'San Telmo',
 'Colegiales',
 'Colegiales',
 'Colegiales',
 'Colegiales',
 'Villa Luro',
 'Barrio Norte',
 'Barrio Norte',
 'Las Cañitas',
 'San Nicolás',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Parque Centenario',
 'Parque Centenario',
 'Villa General Mitre',
 'Almagro',
 'Palermo',
 'Belgrano',
 'Recoleta',
 'Recoleta',
 'Chacarita',
 'Villa Luro',
 'Villa Crespo',
 'Parque Centenario',
 'Parque Centenario',
 'Boca',
 'Once',
 'Flores',
 'Nuñez',
 'Retiro',
 'Retiro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Caballito',
 'Caballito',
 'Monserrat',
 'Monserrat',
 'Monserrat',
 'Monserrat',
 'San Telmo',
 'Colegiales',
 'Colegiales',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Puerto Madero',
 'Puerto Madero',
 'Puerto Madero',
 'San Cristobal',
 'Villa Ortuzar',
 'Villa Urquiza',
 'Parque Chacabuco',
 'Parque Centenario',
 'Parque Centenario',
 'Parque Centenario',
 'Parque Centenario',
 'Centro / Microcentro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Recoleta',
 'Once',
 'Abasto',
 'Flores',
 'Flores',
 'Flores',
 'Nuñez',
 'Retiro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Liniers',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Floresta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Colegiales',
 'Barrio Norte',
 'Barrio Norte',
 'Las Cañitas',
 'San Nicolás',
 'Villa Crespo',
 'Villa Urquiza',
 'Villa Urquiza',
 'Parque Centenario',
 'Parque Centenario',
 'Parque Centenario',
 'Nuñez',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Recoleta',
 'Las Cañitas',
 'Recoleta',
 'Coghlan',
 'Villa Crespo',
 'San Cristobal',
 'Boedo',
 'Retiro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Belgrano',
 'Paternal',
 'Recoleta',
 'Saavedra',
 'Saavedra',
 'Balvanera',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'San Telmo',
 'Colegiales',
 'San Nicolás',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Puerto Madero',
 'Parque Chacabuco',
 'Parque Chacabuco',
 'Parque Chacabuco',
 'Villa Santa Rita',
 'Barracas',
 'Paternal',
 'Caballito',
 'Villa Pueyrredón',
 'Nuñez',
 'Retiro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Caballito',
 'Chacarita',
 'Colegiales',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Urquiza',
 'Villa Urquiza',
 'Parque Chacabuco',
 'Parque Centenario',
 'Caballito',
 'Colegiales',
 'Villa Devoto',
 'Almagro',
 'Almagro',
 'Almagro',
 'Coghlan',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Paternal',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Monserrat',
 'Colegiales',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Villa Ortuzar',
 'Villa Urquiza',
 'Caballito',
 'San Telmo',
 'Villa Crespo',
 'Villa Santa Rita',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Villa Crespo',
 'Boedo',
 'Villa del Parque',
 'Flores',
 'Flores',
 'Palermo',
 'Palermo',
 'Floresta',
 'Balvanera',
 'Caballito',
 'Mataderos',
 'Boca',
 'Nuñez',
 'Palermo',
 'Palermo',
 'Recoleta',
 'Palermo',
 'Retiro',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Chacarita',
 'Las Cañitas',
 'Monte Castro',
 'San Nicolás',
 'Villa Devoto',
 'Constitución',
 'Villa Urquiza',
 'Parque Avellaneda',
 'Villa Pueyrredón',
 'Caballito',
 'Villa Luro',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Urquiza',
 'Saavedra',
 'Boedo',
 'Boedo',
 'Flores',
 'Flores',
 'Flores',
 'Flores',
 'Flores',
 'Nuñez',
 'Nuñez',
 'Retiro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Barracas',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Congreso',
 'Congreso',
 'Congreso',
 'Congreso',
 'Floresta',
 'Paternal',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Saavedra',
 'Saavedra',
 'Balvanera',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'San Telmo',
 'San Telmo',
 'Colegiales',
 'Colegiales',
 'Colegiales',
 'Villa Luro',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Las Cañitas',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'San Cristobal',
 'San Cristobal',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa del Parque',
 'Parque Centenario',
 'Parque Centenario',
 'Villa Pueyrredón',
 'Centro / Microcentro',
 'Palermo',
 'Balvanera',
 'Caballito',
 'Chacarita',
 'Villa Devoto',
 'Boedo',
 'Flores',
 'Flores',
 'Flores',
 'Flores',
 'Flores',
 'Flores',
 'Nuñez',
 'Nuñez',
 'Retiro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Coghlan',
 'Coghlan',
 'Liniers',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Congreso',
 'Congreso',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Saavedra',
 'Balvanera',
 'Balvanera',
 'Balvanera',
 'Balvanera',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Chacarita',
 'Chacarita',
 'Chacarita',
 'Monserrat',
 'San Telmo',
 'Colegiales',
 'Colegiales',
 'Barrio Norte',
 'Las Cañitas',
 'San Nicolás',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Puerto Madero',
 'Puerto Madero',
 'Puerto Madero',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Pueyrredón',
 'Villa General Mitre',
 'Almagro',
 'Recoleta',
 'Balvanera',
 'Villa Urquiza',
 'Villa Pueyrredón',
 'Once',
 'Flores',
 'Flores',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Liniers',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Barracas',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Floresta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Monserrat',
 'Villa Luro',
 'Barrio Norte',
 'Barrio Norte',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Devoto',
 'Constitución',
 'Parque Centenario',
 'Parque Centenario',
 'Parque Centenario',
 'Parque Centenario',
 'Parque Centenario',
 'Parque Centenario',
 'Boedo',
 'Palermo',
 'Balvanera',
 'Caballito',
 'Villa Crespo',
 'Villa Devoto',
 'Almagro',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Monserrat',
 'Parque Centenario',
 'Almagro',
 'Balvanera',
 'Chacarita',
 'Villa Devoto',
 'Palermo',
 'Recoleta',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Recoleta',
 'Chacarita',
 'Villa Crespo',
 'Villa Crespo',
 'San Cristobal',
 'Villa Urquiza',
 'Parque Chacabuco',
 'Parque Centenario',
 'Parque Centenario',
 'Barrio Norte',
 'Villa Crespo',
 'Villa Devoto',
 'Once',
 'Once',
 'Once',
 'Boedo',
 'Abasto',
 'Flores',
 'Retiro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Congreso',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Saavedra',
 'Balvanera',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Caballito',
 'Colegiales',
 'Colegiales',
 'Tribunales',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Puerto Madero',
 'Puerto Madero',
 'San Cristobal',
 'Villa Ortuzar',
 'Villa Urquiza',
 'Villa Urquiza',
 'Velez Sarsfield',
 'Parque Chacabuco',
 'Villa del Parque',
 'Parque Centenario',
 'Parque Centenario',
 'Parque Centenario',
 'Villa Pueyrredón',
 'Almagro',
 'Villa Urquiza',
 'Boedo',
 'Abasto',
 'Flores',
 'Flores',
 'Flores',
 'Flores',
 'Nuñez',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Congreso',
 'Recoleta',
 'Saavedra',
 'Saavedra',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Mataderos',
 'Monserrat',
 'Colegiales',
 'Parque Chas',
 'Barrio Norte',
 'Barrio Norte',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Puerto Madero',
 'San Cristobal',
 'San Cristobal',
 'Villa Ortuzar',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Velez Sarsfield',
 'Velez Sarsfield',
 'Parque Patricios',
 'Parque Centenario',
 'Villa Pueyrredón',
 'Boedo',
 'Almagro',
 'Liniers',
 'Caballito',
 'Barrio Norte',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Devoto',
 'Villa Devoto',
 'Villa Ortuzar',
 'Parque Chacabuco',
 'Villa del Parque',
 'Boedo',
 'Boedo',
 'Boedo',
 'Nuñez',
 'Retiro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Belgrano',
 'Belgrano',
 'Congreso',
 'Congreso',
 'Recoleta',
 'Recoleta',
 'Saavedra',
 'Balvanera',
 'Balvanera',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Chacarita',
 'Colegiales',
 'Colegiales',
 'Colegiales',
 'Barrio Norte',
 'Barrio Norte',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Devoto',
 'Villa Devoto',
 'San Cristobal',
 'San Cristobal',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Velez Sarsfield',
 'Parque Patricios',
 'Parque Centenario',
 'Villa Pueyrredón',
 'Almagro',
 'Almagro',
 'Palermo',
 'Palermo',
 'Caballito',
 'Chacarita',
 'Colegiales',
 'Flores',
 'Flores',
 'Almagro',
 'Almagro',
 'Almagro',
 'Palermo',
 'Belgrano',
 'Recoleta',
 'Recoleta',
 'Recoleta',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Las Cañitas',
 'Villa Crespo',
 'Villa Crespo',
 'San Cristobal',
 'Villa Urquiza',
 'Caballito',
 'Villa del Parque',
 'Flores',
 'Almagro',
 'Palermo',
 'Colegiales',
 'Colegiales',
 'Palermo',
 'Villa Urquiza',
 'Villa Santa Rita',
 'Boca',
 'Boedo',
 'Boedo',
 'Flores',
 'Nuñez',
 'Retiro',
 'Almagro',
 'Almagro',
 'Almagro',
 'Coghlan',
 'Liniers',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Palermo',
 'Barracas',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Belgrano',
 'Floresta',
 'Recoleta',
 'Recoleta',
 'Balvanera',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Caballito',
 'Chacarita',
 'Chacarita',
 'Mataderos',
 'San Telmo',
 'Colegiales',
 'Barrio Norte',
 'Barrio Norte',
 'Barrio Norte',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Crespo',
 'Villa Devoto',
 'Puerto Madero',
 'Villa Ortuzar',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Villa Urquiza',
 'Parque Patricios',
 'Villa del Parque',
 'Villa del Parque',
 'Villa General Mitre',
 'Boedo',
 'Nuñez',
 'Almagro',
 'Palermo',
 'Palermo',
 'Paternal',
 'Saavedra',
 'Colegiales',
 'Parque Chas',
 'Villa Urquiza',
 'Villa del Parque']
barrios2=['Boedo', 'Palermo', 'Villa Crespo', 'Parque Patricios',
       'Villa Pueyrredón', 'Abasto', 'Flores', 'Nuñez', 'Almagro',
       'Belgrano', 'Floresta', 'Recoleta', 'Balvanera', 'Caballito',
       'Chacarita', 'San Telmo', 'Colegiales', 'Villa Luro',
       'Barrio Norte', 'Las Cañitas', 'San Nicolás', 'Villa Urquiza',
       'Parque Centenario', 'Villa General Mitre', 'Boca', 'Once',
       'Retiro', 'Monserrat', 'Puerto Madero', 'San Cristobal',
       'Villa Ortuzar', 'Parque Chacabuco', 'Centro / Microcentro',
       'Liniers', 'Coghlan', 'Paternal', 'Saavedra', 'Villa Santa Rita',
       'Barracas', 'Villa Devoto', 'Villa del Parque', 'Mataderos',
       'Monte Castro', 'Constitución', 'Parque Avellaneda', 'Congreso',
       'Tribunales', 'Velez Sarsfield', 'Parque Chas', 'Versalles',
       'Agronomía', 'Villa Lugano', 'Pompeya', 'Villa Real', 'Catalinas',
       'Villa Riachuelo', 'Villa Soldati']
columna=[]
for i in barrios:
    if i=='Boedo':
        x=1
        columna.append(x)
    if i=='Palermo':
        x=2
        columna.append(x)
    if i=='Villa Crespo':
        x=3
        columna.append(x)
    if i=='Parque Patricios':
        x=4
        columna.append(x)
    if i=='Villa Pueyrredón':
        x=5
        columna.append(x)
    if i=='Abasto':
        x=6
        columna.append(x)
    if i=='Flores':
        x=7
        columna.append(x)
    if i=='Nuñez':
        x=8
        columna.append(x)
    if i=='Almagro':
        x=9
        columna.append(x)
    if i=='Belgrano':
        x=10
        columna.append(x)
    if i=='Floresta':
        x=11
        columna.append(x)
    if i=='Recoleta':
        x=12
        columna.append(x)
    if i=='Balvanera':
        x=13
        columna.append(x)
    if i=='Caballito':
        x=14       
        columna.append(x)
    if i=='Chacarita':
        x=15
        columna.append(x)
    if i=='San Telmo':
        x=16
        columna.append(x)
    if i=='Colegiales':
        x=17
        columna.append(x)
    if i=='Villa Luro':
        x=18
        columna.append(x)
    if i=='Barrio Norte':
        x=19
        columna.append(x)
    if i=='Las Cañitas':
        x=20
        columna.append(x)
    if i=='San Nicolás':
        x=21
        columna.append(x)
    if i=='Villa Urquiza':
        x=22
        columna.append(x)
    if i=='Parque Centenario':
        x=23
        columna.append(x)
    if i=='Villa General Mitre':
        x=24
        columna.append(x)
    if i=='Boca':
        x=25
        columna.append(x)
    if i=='Once':
        x=26
        columna.append(x)
    if i=='Retiro':
        x=27
        columna.append(x)
    if i=='Monserrat':
        x=28
        columna.append(x)
    if i=='Puerto Madero':
        x=29
        columna.append(x)
    if i=='San Cristobal':
        x=30
        columna.append(x)
    if i=='Villa Ortuzar':
        x=31
        columna.append(x)
    if i=='Parque Chacabuco':
        x=32
        columna.append(x)
    if i=='Centro / Microcentro':
        x=33
        columna.append(x)
    if i=='Liniers':
        x=34
        columna.append(x)
    if i=='Coghlan':
        x=35
        columna.append(x)
    if i=='Paternal':
        x=36
        columna.append(x)
    if i=='Saavedra':
        x=37
        columna.append(x)
    if i=='Villa Santa Rita':
        x=38
        columna.append(x)
    if i=='Barracas':
        x=39
        columna.append(x)
    if i=='Villa Devoto':
        x=40
        columna.append(x)
    if i=='Villa del Parque':
        x=41
        columna.append(x)
    if i=='Mataderos':
        x=42
        columna.append(x)
    if i=='Monte Castro':
        x=43
        columna.append(x)
    if i=='Constitución':
        x=44
        columna.append(x)
    if i=='Parque Avellaneda':
        x=45
        columna.append(x)
    if i=='Congreso':
        x=46
        columna.append(x)
    if i=='Tribunales':
        x=47
        columna.append(x)
    if i=='Velez Sarsfield':
        x=48
        columna.append(x)
    if i=='Parque Chas':
        x=49
        columna.append(x)
    if i=='Versalles':
        x=50
        columna.append(x)
    if i=='Agronomía':
        x=51
        columna.append(x)
    if i=='Villa Lugano':
        x=52
        columna.append(x)
    if i=='Pompeya':
        x=53
        columna.append(x)
    if i=='Villa Real':
        x=54
        columna.append(x)
    if i=='Catalinas':
        x=55
        columna.append(x)
    if i=='Villa Riachuelo':
        x=56
        columna.append(x)
    if i=='Villa Soldati':
        x=57
        columna.append(x)
    #else:
     #   x=0
    
    #columna.append(x)
#print (columna)
propiedades=['PH', 'Departamento', 'Casa']
pili=[]
for j in propiedades:
    if j =='PH':
        y=1
        pili.append(y)
    if j=='Departamento':
        y=2
        pili.append(y)
    if j=='Casa':
        y=3
        pili.append(y)
print(pili)        
    
